 #Minimal Docker Compose cluster for ElasticSearch and Kibana
# Put this file any folder creating "logs" and "esdata" folders
# to persist the cluster indices and kibana state

version: "3.7"

services:
  opensky-loader:
    init: true
    build: ./opensky-loader/
    container_name: opensky-loader
    volumes:
      - ./certs/ca/ca.crt:/etc/ssl/opensky/ca/ca.crt:ro
      - ./opensky-loader/index.js:/usr/src/app/index.js
      - ./elastic-config.js:/usr/src/app/config.js
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - OPENSKY_USER=${OPENSKY_USER}
      - OPENSKY_PASSWORD=${OPENSKY_PASSWORD}

  opensky-viewer:
    init: true
    build: ./opensky-viewer/
    container_name: opensky-viewer
    environment:
      - ELASTIC_HOST=${ELASTIC_HOST}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - PORT=3000
    ports:
      - $OPENSKY_VIEWER_PORT:3000
    volumes:
      - ./certs/ca/ca.crt:/etc/ssl/opensky/ca/ca.crt:ro
      - ./opensky-viewer/index.js:/usr/src/app/index.js
      - ./opensky-viewer/index.html:/usr/src/app/index.html
      - ./elastic-config.js:/usr/src/app/config.js

